In [1]:
import pandas as pd
import numpy as np

In [2]:
x_mat = np.array([[1,1200,600],[1,1250,700],[1,2300,1200],[1,1542,850],[1,1248,775]])
x_mat

array([[   1, 1200,  600],
       [   1, 1250,  700],
       [   1, 2300, 1200],
       [   1, 1542,  850],
       [   1, 1248,  775]])

In [3]:
y_mat = np.array([10000,12000,20000,25000,23000])
y_mat

array([10000, 12000, 20000, 25000, 23000])

In [4]:
x_mat.shape

(5, 3)

In [5]:
coeffs = np.matmul(np.linalg.inv(np.matmul(x_mat.T,x_mat)),np.matmul(x_mat.T,y_mat))
coeffs

array([1088.93358771,  -37.82161132,   89.63158337])

In [6]:
x1 = np.array([1200,1250,2300,1542,1248])
x2 = np.array([600,700,1200,850,775])
x = np.column_stack((x1, x2))
y = np.array([10000,12000,20000,25000,23000])

In [7]:
x

array([[1200,  600],
       [1250,  700],
       [2300, 1200],
       [1542,  850],
       [1248,  775]])

In [8]:
x.shape

(5, 2)

In [9]:
y.shape

(5,)

In [10]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x,y)

LinearRegression()

In [11]:
model.coef_

array([-37.82161132,  89.63158337])

In [12]:
model.intercept_

1088.9335877128979

In [13]:
df = pd.DataFrame({'dist':x1,'fuel': x2,'price':y})
df

dist  fuel  price
0  1200   600  10000
1  1250   700  12000
2  2300  1200  20000
3  1542   850  25000
4  1248   775  23000

In [14]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [15]:
inp = df[['dist','fuel']]

In [16]:
vif_inp = pd.DataFrame()
vif_inp['feature'] = inp.columns
vif_inp

feature
0    dist
1    fuel

In [23]:
vif_inp['vif'] = [variance_inflation_factor(inp.values,i) for i in range(inp.columns.shape[0])]
vif_inp

feature         vif
0    dist  238.694764
1    fuel  238.694764