In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [2]:
df = pd.read_csv("rain.csv")
df.head()

pressure   humidity       temp  rain
0  1010.227307  60.544759  20.758588     0
1  1020.845676  75.458283  22.032115     1
2  1015.654002  80.300858  18.647099     1
3  1018.525788  50.815060  25.064591     0
4  1025.001878  65.258981  30.152402     0

In [3]:
log1 = df[['pressure','rain']]

In [4]:
model = LinearRegression()

In [5]:
model.fit(np.array(df['pressure']).reshape(-1,1), df['rain'])

LinearRegression()

In [6]:
model.coef_[0]

-0.029059742179349632

In [7]:
model.intercept_

29.933230794704947

In [8]:
z = [model.coef_[0] * val + model.intercept_ for val in df['pressure']]

In [9]:
def to_sigmoid(z):
    y = 1/(1+(np.exp(-z)))
    return y

In [10]:
z_sig = [to_sigmoid(val) for val in z ]

In [11]:
z_sig = np.array(z_sig)
z_sig

array([0.6402123 , 0.56653275, 0.60314516, 0.58300803, 0.53666917,
       0.6518943 , 0.62468582, 0.55525312, 0.66974133, 0.49862759,
       0.63231065, 0.66026183, 0.54705068, 0.61986033, 0.57320725,
       0.52617334, 0.64409828, 0.59292037, 0.53869665, 0.61383627,
       0.61845746, 0.63572196, 0.54828264, 0.6438201 , 0.55595647,
       0.6062222 , 0.65383411, 0.56402958, 0.60048319, 0.63303404,
       0.66562595, 0.57022471, 0.61331542, 0.65810045, 0.54420592,
       0.62450545, 0.53100385, 0.63639088, 0.6534089 , 0.5995695 ,
       0.65808376, 0.56735218, 0.57659079, 0.60704036, 0.56105504,
       0.60787446, 0.55052816, 0.62504555, 0.63123615, 0.644791  ,
       0.54001013, 0.5807962 , 0.57236062, 0.62746474])

In [12]:
yhat = np.where(z_sig>0.5,1,0)

In [13]:
yhat

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [14]:
log2 = df[['humidity','rain']]

In [15]:
model = LinearRegression()

In [16]:
model.fit(np.array(df['humidity']).reshape(-1,1), df['rain'])

LinearRegression()

In [17]:
model.coef_

array([0.02863402])

In [18]:
model.intercept_

-1.659167658767355

In [19]:
def to_sigmoid(z):
    y = 1/(1+(np.exp(-z)))
    return y

In [20]:
z = [model.coef_[0] * val + model.intercept_ for val in df['humidity']]

In [21]:
z_sig1 =  [to_sigmoid(val) for val in z]

In [22]:
z_sig1 = np.array(z_sig1)
z_sig1

array([0.51860946, 0.62281327, 0.65479161, 0.44914443, 0.55217423,
       0.68670539, 0.47957798, 0.58853638, 0.71791742, 0.3786259 ,
       0.64465339, 0.70734365, 0.53598485, 0.66420762, 0.48540181,
       0.57444775, 0.72740306, 0.55359295, 0.61988247, 0.66128244,
       0.57090224, 0.67142371, 0.47722848, 0.65690371, 0.48896213,
       0.6502135 , 0.68618016, 0.58857164, 0.53622807, 0.641792  ,
       0.67966916, 0.63758884, 0.51541735, 0.59435867, 0.6471242 ,
       0.56113438, 0.55633505, 0.64583351, 0.66861258, 0.61628688,
       0.65573185, 0.55576714, 0.58791616, 0.55909826, 0.51650046,
       0.59081848, 0.68478144, 0.64838201, 0.59510256, 0.61229902,
       0.55054976, 0.66081656, 0.61953619, 0.56887359])

In [23]:
yhat = np.where(z_sig1>0.5,1,0)

In [24]:
yhat

array([1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [25]:
log3 = df[['temp','rain']]

In [26]:
model = LinearRegression()

In [27]:
model.fit(np.array(df['temp']).reshape(-1,1), df['rain'])

LinearRegression()

In [28]:
model.coef_[0]

-0.06897844469356275

In [29]:
model.intercept_

1.9792630007974468

In [30]:
def to_sig(z):
    y = 1/(1 + (np.exp(-z)))
    return y

In [31]:
z= [model.coef_[0]* val + model.intercept_ for val in df['temp']]


In [32]:
z_sig2 = [to_sig(val) for val in z]

In [33]:
z_sig2 = np.array(z_sig2)
z_sig2

array([0.6335247 , 0.61290077, 0.66663732, 0.56226178, 0.4748705 ,
       0.66079637, 0.62731232, 0.59663694, 0.67726952, 0.49696076,
       0.62104508, 0.65405262, 0.61087931, 0.61690918, 0.57871218,
       0.53832426, 0.66575125, 0.63116576, 0.49200362, 0.65852104,
       0.60148419, 0.62388349, 0.67328321, 0.54052353, 0.59237263,
       0.64600096, 0.63719051, 0.52175205, 0.5823065 , 0.5684878 ,
       0.60698915, 0.64693077, 0.49190466, 0.67830267, 0.62023224,
       0.54599724, 0.64532559, 0.64814951, 0.60533134, 0.52345611,
       0.60220058, 0.67315869, 0.60101001, 0.6293452 , 0.53412091,
       0.49106763, 0.57880093, 0.61010722, 0.55677096, 0.5166421 ,
       0.61064826, 0.64307452, 0.65850883, 0.58230107])

In [34]:
yhat = np.where(z_sig2>0.5,1,0)

In [35]:
yhat

array([1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1])

In [36]:
from sklearn.metrics import accuracy_score , r2_score

In [37]:
a = accuracy_score(df['rain'],yhat)
a

0.5

In [38]:
from sklearn.linear_model import LogisticRegression

In [39]:
mod = LogisticRegression()

In [40]:
x = df[['pressure','humidity','temp']]
y = df['rain']

In [41]:
mod.fit(x,y)

LogisticRegression()

In [42]:
mod.score(x,y)

0.8148148148148148

In [43]:
yhat = mod.predict(x)

In [44]:
b = r2_score(y,yhat)
b

0.2329545454545453