In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import Ridge,LinearRegression,Lasso,ElasticNet
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

In [2]:
np.set_printoptions(suppress=True)

In [3]:
df = pd.read_csv('regu.csv')
df.head()

a    b     c   y
0  4045  557  0.74  48
1  6347  112  0.09  99
2  3185  318  0.22  84
3  2069  922  0.64  95
4  9644  544  0.15  25

In [4]:
x = df.loc[:,:'c']
y = df['y']

In [5]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3,random_state=96)

In [6]:
r2 = []

In [7]:
lin_mod  = LinearRegression()
lin_mod.fit(x_train,y_train)
coef1 = lin_mod.coef_
ypred = lin_mod.predict(x_test)
r2.append(r2_score(y_test,ypred))
print(coef1)

[-0.00024807  0.00010452 -3.95098334]


In [8]:
las_mod = Lasso(alpha = 0.5)
las_mod.fit(x_train,y_train)
coef2 = las_mod.coef_
ypred = las_mod.predict(x_test)
r2.append(r2_score(y_test,ypred))
print(coef2)

[-0.00026218  0.00022084 -0.        ]


In [9]:
rid_mod = Ridge(alpha = 0.5)
rid_mod.fit(x_train,y_train)
coef3 = rid_mod.coef_
ypred = rid_mod.predict(x_test)
r2.append(r2_score(y_test,ypred))
print(coef3)

[-0.00024819  0.00010557 -3.91744087]


In [10]:
el_mod = ElasticNet(alpha = 0.5)
el_mod.fit(x_train,y_train)
coef4 = el_mod.coef_
ypred = el_mod.predict(x_test)
r2.append(r2_score(y_test,ypred))
print(coef4)

[-0.00026136  0.00021709 -0.23875667]


In [11]:
tab = pd.DataFrame({'Model':['Linear','Lasso','Ridge','Elastic Net'],'B1':[coef1[0],coef2[0],coef3[0],coef4[0]], 'B2' :[coef1[1],coef2[1],coef3[1],coef4[1]],'B3': [coef1[2],coef2[2],coef3[2],coef4[2]]})


In [12]:
tab

Model        B1        B2        B3
0       Linear -0.000248  0.000105 -3.950983
1        Lasso -0.000262  0.000221 -0.000000
2        Ridge -0.000248  0.000106 -3.917441
3  Elastic Net -0.000261  0.000217 -0.238757

In [13]:
tab['r2_score'] = r2
tab

Model        B1        B2        B3  r2_score
0       Linear -0.000248  0.000105 -3.950983  0.004934
1        Lasso -0.000262  0.000221 -0.000000 -0.000048
2        Ridge -0.000248  0.000106 -3.917441  0.004905
3  Elastic Net -0.000261  0.000217 -0.238757  0.000344